In [3]:
from sklearn.pipeline import Pipeline
##feature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [5]:
steps=[("standard_scaler",StandardScaler()),
      ("classifier", LogisticRegression())]

In [7]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [11]:
pipe=Pipeline(steps)
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [27]:
#creating a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [29]:
X.shape

(1000, 20)

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [35]:
X_train

array([[-0.1416975 ,  0.69832868, -0.3967222 , ..., -0.22431158,
        -0.50384032,  0.59334173],
       [ 0.26548931,  0.78992044, -0.14853385, ...,  0.43781367,
         0.53094111, -0.03111208],
       [ 0.24925924, -0.0113437 , -2.69609403, ...,  1.24008823,
        -0.69208658, -1.04609272],
       ...,
       [-0.0334776 ,  0.47948442,  1.30555805, ...,  0.83701059,
         1.6714742 , -1.72840843],
       [-0.20267484,  0.14533026, -0.21938785, ...,  0.41736326,
         0.84684555,  0.51645725],
       [-0.37845355, -0.61590185,  0.1799429 , ...,  0.09310881,
         1.03200584,  2.53656167]])

In [41]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [43]:
y_pred=pipe.predict(X_test)

In [45]:
y_pred

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

## Example 2
 Displaying a pipeline with standard scaler, dimentionality reduction and then estimator

In [50]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [52]:
steps=[("scaling",StandardScaler()),
      ("PCA", PCA(n_components=3)),
      ("SVC", SVC())]

In [56]:
pipe2=Pipeline(steps)
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [60]:
#pipe2['scaling'].fit_transform(X_train)
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [62]:
pipe2.predict(X_test)

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

## Complex example (IMP)


In [69]:
from sklearn.impute import SimpleImputer #to fill missing values for numerical values

In [75]:
#numerical processing pipeline
import numpy as np
numeric_processor= Pipeline(
steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy='mean')),
      ("scaler",StandardScaler())]
)

In [79]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [85]:
#categorical processing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor= Pipeline(
steps=[("imputation_contant",SimpleImputer(fill_value="missing",strategy="contant")),
      ("onehot",OneHotEncoder(handle_unknown='ignore'))]
)

In [87]:
categorical_processor

Pipeline(steps=[('imputation_contant',
                 SimpleImputer(fill_value='missing', strategy='contant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [89]:
#combining both the pipelines
from sklearn.compose import ColumnTransformer

In [93]:
preprocessor= ColumnTransformer(
    [("categorical",categorical_processor,['gender','city'],
     ("numerical"),numeric_processor,['age','height'])]
)

In [95]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_contant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='contant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city'], 'numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [97]:
from sklearn.pipeline import make_pipeline

In [99]:
pipe=make_pipeline(preprocessor, LogisticRegression())
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_contant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='contant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city'],
                                                  'numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])